// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $admin_layout from "./routes/admin/_layout.tsx";
import * as $admin_create_question from "./routes/admin/create-question.tsx";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $admin_profile from "./routes/admin/profile.tsx";
import * as $admin_questions from "./routes/admin/questions.tsx";
import * as $admin_subjects from "./routes/admin/subjects.tsx";
import * as $api_ai_ask from "./routes/api/ai/ask.ts";
import * as $api_ai_explain from "./routes/api/ai/explain.ts";
import * as $api_assignments_create_practice from "./routes/api/assignments/create-practice.ts";
import * as $api_assignments_create from "./routes/api/assignments/create.ts";
import * as $api_auth_change_password from "./routes/api/auth/change-password.ts";
import * as $api_auth_login from "./routes/api/auth/login.ts";
import * as $api_auth_logout from "./routes/api/auth/logout.ts";
import * as $api_auth_me from "./routes/api/auth/me.ts";
import * as $api_auth_register from "./routes/api/auth/register.ts";
import * as $api_auth_update_profile from "./routes/api/auth/update_profile.ts";
import * as $api_auth_verify_email from "./routes/api/auth/verify-email.ts";
import * as $api_class_leave from "./routes/api/class/leave.ts";
import * as $api_classes_id_ from "./routes/api/classes/[id].ts";
import * as $api_classes_index from "./routes/api/classes/index.ts";
import * as $api_classes_join from "./routes/api/classes/join.ts";
import * as $api_documents_export_pdf from "./routes/api/documents/export-pdf.ts";
import * as $api_exam_export_pdf from "./routes/api/exam/export-pdf.ts";
import * as $api_exam_generate from "./routes/api/exam/generate.ts";
import * as $api_exam_grade_submission from "./routes/api/exam/grade-submission.ts";
import * as $api_exam_submit from "./routes/api/exam/submit.ts";
import * as $api_questions_id_ from "./routes/api/questions/[id].ts";
import * as $api_questions_available from "./routes/api/questions/available.ts";
import * as $api_questions_create from "./routes/api/questions/create.ts";
import * as $api_questions_export_document from "./routes/api/questions/export-document.ts";
import * as $api_questions_export_pdf from "./routes/api/questions/export-pdf.ts";
import * as $api_questions_import from "./routes/api/questions/import.ts";
import * as $api_questions_index from "./routes/api/questions/index.ts";
import * as $api_questions_update from "./routes/api/questions/update.ts";
import * as $api_textbook_lessons from "./routes/api/textbook/lessons.ts";
import * as $api_textbook_subjects from "./routes/api/textbook/subjects.ts";
import * as $api_textbook_topics from "./routes/api/textbook/topics.ts";
import * as $change_password from "./routes/change-password.tsx";
import * as $class_classId_e_exerciseId_ from "./routes/class/[classId]/e/[exerciseId].tsx";
import * as $class_id_e_exam_id_r_index from "./routes/class/[id]/e/[exam_id]/r/index.tsx";
import * as $class_index from "./routes/class/index.tsx";
import * as $exam_exercise from "./routes/exam/exercise.tsx";
import * as $exam_practice_id_ from "./routes/exam/practice/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $register from "./routes/register.tsx";
import * as $student_layout from "./routes/student/_layout.tsx";
import * as $student_ask_ai from "./routes/student/ask-ai.tsx";
import * as $student_classes from "./routes/student/classes.tsx";
import * as $student_exam from "./routes/student/exam.tsx";
import * as $student_exam_practice from "./routes/student/exam/practice.tsx";
import * as $student_index from "./routes/student/index.tsx";
import * as $student_profile from "./routes/student/profile.tsx";
import * as $teacher_layout from "./routes/teacher/_layout.tsx";
import * as $teacher_ask_ai from "./routes/teacher/ask-ai.tsx";
import * as $teacher_assignments_create from "./routes/teacher/assignments/create.tsx";
import * as $teacher_class_id_e_exam_id_r_index from "./routes/teacher/class/[id]/e/[exam_id]/r/index.tsx";
import * as $teacher_classes from "./routes/teacher/classes.tsx";
import * as $teacher_create_test from "./routes/teacher/create-test.tsx";
import * as $teacher_document_bank from "./routes/teacher/document-bank.tsx";
import * as $teacher_exam from "./routes/teacher/exam.tsx";
import * as $teacher_grading_id_ from "./routes/teacher/grading/[id].tsx";
import * as $teacher_grading_index from "./routes/teacher/grading/index.tsx";
import * as $teacher_index from "./routes/teacher/index.tsx";
import * as $teacher_profile from "./routes/teacher/profile.tsx";
import * as $unauthorized from "./routes/unauthorized.tsx";
import * as $AdminDashboardManager from "./islands/AdminDashboardManager.tsx";
import * as $AdminSubjectManager from "./islands/AdminSubjectManager.tsx";
import * as $AskAI from "./islands/AskAI.tsx";
import * as $ClassDetail from "./islands/ClassDetail.tsx";
import * as $CreateAssignmentForm from "./islands/CreateAssignmentForm.tsx";
import * as $CreateQuestionForm from "./islands/CreateQuestionForm.tsx";
import * as $CreateTestForm from "./islands/CreateTestForm.tsx";
import * as $DashboardLayout from "./islands/DashboardLayout.tsx";
import * as $DocumentBankIsland from "./islands/DocumentBankIsland.tsx";
import * as $ExamExercise from "./islands/ExamExercise.tsx";
import * as $ExamResultsIsland from "./islands/ExamResultsIsland.tsx";
import * as $GradingForm from "./islands/GradingForm.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $PasswordChangeForm from "./islands/PasswordChangeForm.tsx";
import * as $PracticeForm from "./islands/PracticeForm.tsx";
import * as $ProfileForm from "./islands/ProfileForm.tsx";
import * as $QuestionBankManager from "./islands/QuestionBankManager.tsx";
import * as $RegisterForm from "./islands/RegisterForm.tsx";
import * as $StudentAskAI from "./islands/StudentAskAI.tsx";
import * as $StudentClasses from "./islands/StudentClasses.tsx";
import * as $TeacherAskAI from "./islands/TeacherAskAI.tsx";
import * as $TeacherClasses from "./islands/TeacherClasses.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/admin/_layout.tsx": $admin_layout,
    "./routes/admin/create-question.tsx": $admin_create_question,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/admin/profile.tsx": $admin_profile,
    "./routes/admin/questions.tsx": $admin_questions,
    "./routes/admin/subjects.tsx": $admin_subjects,
    "./routes/api/ai/ask.ts": $api_ai_ask,
    "./routes/api/ai/explain.ts": $api_ai_explain,
    "./routes/api/assignments/create-practice.ts":
      $api_assignments_create_practice,
    "./routes/api/assignments/create.ts": $api_assignments_create,
    "./routes/api/auth/change-password.ts": $api_auth_change_password,
    "./routes/api/auth/login.ts": $api_auth_login,
    "./routes/api/auth/logout.ts": $api_auth_logout,
    "./routes/api/auth/me.ts": $api_auth_me,
    "./routes/api/auth/register.ts": $api_auth_register,
    "./routes/api/auth/update_profile.ts": $api_auth_update_profile,
    "./routes/api/auth/verify-email.ts": $api_auth_verify_email,
    "./routes/api/class/leave.ts": $api_class_leave,
    "./routes/api/classes/[id].ts": $api_classes_id_,
    "./routes/api/classes/index.ts": $api_classes_index,
    "./routes/api/classes/join.ts": $api_classes_join,
    "./routes/api/documents/export-pdf.ts": $api_documents_export_pdf,
    "./routes/api/exam/export-pdf.ts": $api_exam_export_pdf,
    "./routes/api/exam/generate.ts": $api_exam_generate,
    "./routes/api/exam/grade-submission.ts": $api_exam_grade_submission,
    "./routes/api/exam/submit.ts": $api_exam_submit,
    "./routes/api/questions/[id].ts": $api_questions_id_,
    "./routes/api/questions/available.ts": $api_questions_available,
    "./routes/api/questions/create.ts": $api_questions_create,
    "./routes/api/questions/export-document.ts": $api_questions_export_document,
    "./routes/api/questions/export-pdf.ts": $api_questions_export_pdf,
    "./routes/api/questions/import.ts": $api_questions_import,
    "./routes/api/questions/index.ts": $api_questions_index,
    "./routes/api/questions/update.ts": $api_questions_update,
    "./routes/api/textbook/lessons.ts": $api_textbook_lessons,
    "./routes/api/textbook/subjects.ts": $api_textbook_subjects,
    "./routes/api/textbook/topics.ts": $api_textbook_topics,
    "./routes/change-password.tsx": $change_password,
    "./routes/class/[classId]/e/[exerciseId].tsx": $class_classId_e_exerciseId_,
    "./routes/class/[id]/e/[exam_id]/r/index.tsx": $class_id_e_exam_id_r_index,
    "./routes/class/index.tsx": $class_index,
    "./routes/exam/exercise.tsx": $exam_exercise,
    "./routes/exam/practice/[id].tsx": $exam_practice_id_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/register.tsx": $register,
    "./routes/student/_layout.tsx": $student_layout,
    "./routes/student/ask-ai.tsx": $student_ask_ai,
    "./routes/student/classes.tsx": $student_classes,
    "./routes/student/exam.tsx": $student_exam,
    "./routes/student/exam/practice.tsx": $student_exam_practice,
    "./routes/student/index.tsx": $student_index,
    "./routes/student/profile.tsx": $student_profile,
    "./routes/teacher/_layout.tsx": $teacher_layout,
    "./routes/teacher/ask-ai.tsx": $teacher_ask_ai,
    "./routes/teacher/assignments/create.tsx": $teacher_assignments_create,
    "./routes/teacher/class/[id]/e/[exam_id]/r/index.tsx":
      $teacher_class_id_e_exam_id_r_index,
    "./routes/teacher/classes.tsx": $teacher_classes,
    "./routes/teacher/create-test.tsx": $teacher_create_test,
    "./routes/teacher/document-bank.tsx": $teacher_document_bank,
    "./routes/teacher/exam.tsx": $teacher_exam,
    "./routes/teacher/grading/[id].tsx": $teacher_grading_id_,
    "./routes/teacher/grading/index.tsx": $teacher_grading_index,
    "./routes/teacher/index.tsx": $teacher_index,
    "./routes/teacher/profile.tsx": $teacher_profile,
    "./routes/unauthorized.tsx": $unauthorized,
  },
  islands: {
    "./islands/AdminDashboardManager.tsx": $AdminDashboardManager,
    "./islands/AdminSubjectManager.tsx": $AdminSubjectManager,
    "./islands/AskAI.tsx": $AskAI,
    "./islands/ClassDetail.tsx": $ClassDetail,
    "./islands/CreateAssignmentForm.tsx": $CreateAssignmentForm,
    "./islands/CreateQuestionForm.tsx": $CreateQuestionForm,
    "./islands/CreateTestForm.tsx": $CreateTestForm,
    "./islands/DashboardLayout.tsx": $DashboardLayout,
    "./islands/DocumentBankIsland.tsx": $DocumentBankIsland,
    "./islands/ExamExercise.tsx": $ExamExercise,
    "./islands/ExamResultsIsland.tsx": $ExamResultsIsland,
    "./islands/GradingForm.tsx": $GradingForm,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/PasswordChangeForm.tsx": $PasswordChangeForm,
    "./islands/PracticeForm.tsx": $PracticeForm,
    "./islands/ProfileForm.tsx": $ProfileForm,
    "./islands/QuestionBankManager.tsx": $QuestionBankManager,
    "./islands/RegisterForm.tsx": $RegisterForm,
    "./islands/StudentAskAI.tsx": $StudentAskAI,
    "./islands/StudentClasses.tsx": $StudentClasses,
    "./islands/TeacherAskAI.tsx": $TeacherAskAI,
    "./islands/TeacherClasses.tsx": $TeacherClasses,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
